"""
Framework-wide constants for the CRM Dataset Build Framework.

This module contains application metadata, directory paths,
default values, filenames, formatting rules, and shared constants
used throughout the framework.
"""

from __future__ import annotations

from pathlib import Path

# ==========================================================================
# Framework Information
# ==========================================================================

FRAMEWORK_NAME = "CRM Dataset Build Framework"

FRAMEWORK_VERSION = "0.1.0-alpha"

PYTHON_MINIMUM_VERSION = (3, 11)

# ==========================================================================
# Character Encoding
# ==========================================================================

ENCODING = "utf-8"

LINE_ENDING = "\n"

# ==========================================================================
# Formatting
# ==========================================================================

DEFAULT_INDENT = 4

HEADER_WIDTH = 88

HEADER_SEPARATOR = "=" * HEADER_WIDTH

# ==========================================================================
# Date and Time Formats
# ==========================================================================

TIMESTAMP_FORMAT = "%Y-%m-%d %H:%M:%S"

DATE_FORMAT = "%Y-%m-%d"

TIME_FORMAT = "%H:%M:%S"

# ==========================================================================
# Project Directories
# ==========================================================================

ROOT_DIR = Path(__file__).resolve().parents[1]

DATA_DIR = ROOT_DIR / "data"

GENERATED_DIR = ROOT_DIR / "generated"

LOG_DIR = ROOT_DIR / "logs"

REPORT_DIR = ROOT_DIR / "reports"

BACKUP_DIR = ROOT_DIR / "backups"

# ==========================================================================
# Dataset Naming Convention
# ==========================================================================

DATASET_PART_SUFFIXES = (
    "part1A",
    "part1B",
    "part2A",
    "part2B",
)

DEFAULT_OUTPUT_EXTENSION = ".py"

# ==========================================================================
# Dataset Defaults
# ==========================================================================

DEFAULT_PART_COUNT = len(DATASET_PART_SUFFIXES)

DEFAULT_RECORDS_PER_PART = 25

DEFAULT_TOTAL_RECORDS = (
    DEFAULT_PART_COUNT *
    DEFAULT_RECORDS_PER_PART
)

# ==========================================================================
# Supported File Types
# ==========================================================================

SUPPORTED_DATASET_EXTENSIONS = (
    ".py",
)

SUPPORTED_OUTPUT_EXTENSIONS = (
    ".py",
)

# ==========================================================================
# Report Files
# ==========================================================================

BUILD_LOG_FILENAME = "build.log"

BUILD_REPORT_FILENAME = "build_report.txt"

VALIDATION_REPORT_FILENAME = "validation_report.txt"

SUMMARY_REPORT_FILENAME = "summary_report.txt"

# ==========================================================================
# Default Paths
# ==========================================================================

DEFAULT_LOG_FILE = LOG_DIR / BUILD_LOG_FILENAME

DEFAULT_REPORT_FILE = REPORT_DIR / BUILD_REPORT_FILENAME

DEFAULT_VALIDATION_REPORT = (
    REPORT_DIR /
    VALIDATION_REPORT_FILENAME
)

DEFAULT_SUMMARY_REPORT = (
    REPORT_DIR /
    SUMMARY_REPORT_FILENAME
)

# ==========================================================================
# Generated File Header
# ==========================================================================

AUTO_GENERATED_WARNING = (
    "WARNING: This file was generated automatically. "
    "Do not edit this file manually."
)

OUTPUT_HEADER_TEMPLATE = '''"""
Generated by {framework_name}

Framework Version : {framework_version}
Dataset           : {dataset_name}
Generated On      : {generated_on}

{warning}
"""
'''

# ==========================================================================
# Logging
# ==========================================================================

LOG_FORMAT = (
    "%(asctime)s | %(levelname)-8s | %(message)s"
)

LOG_DATE_FORMAT = TIMESTAMP_FORMAT

# ==========================================================================
# Standard Messages
# ==========================================================================

MSG_BUILD_STARTED = "Dataset build started."

MSG_LOADING_DATASET = "Loading dataset."

MSG_VALIDATION_STARTED = "Validation started."

MSG_VALIDATION_COMPLETED = "Validation completed."

MSG_MERGING_DATASET = "Merging dataset."

MSG_WRITING_OUTPUT = "Writing output dataset."

MSG_BUILD_COMPLETED = "Dataset build completed successfully."

# ==========================================================================
# Exit Codes
# ==========================================================================

EXIT_SUCCESS = 0

EXIT_FAILURE = 1